# __5-Python Homework__

## __1.What does Pandas stand for?__
### The word Pandas is derived from the word Panel Data. 

## __2. What are the 2 collections used in Pandas?__
### The two collections used in Pandas is "Series" and "Dataframes". 

## __3. Name 4 things Pandas can do for us.__
### Four things that Pandas can do for us for data analysis is load, manipulate, prepare, and analyze. 

## __4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?__
### 

## __5. What is a CSV?__
### CSV is a file that stands for comma seperated files. 

## __6. When cleaning data what values do we not like in our data?__
### When cleaning data, the values that we do not like in our data is called Nulls. They are columns without data. We can drop Nulls by using the .dropna() method. 


In [45]:
import numpy as np 

array1=np.array([[25,16]])
array2=np.array([[11,2],[13,4]])
array3=np.array([[7,81],[5,6],[11,12]])

newArray=np.concatenate((array1,array2,array3), axis=0)
sortedArray=np.sort(newArray)
reshapedArray=sortedArray.reshape(2,2,3)
a,b=reshapedArray
a0,a1=a
b0,b1=b

print("\n1. New array: \n", newArray)
print("\n2. Sorted Array: \n", sortedArray)
print("\n3. Reshaped Array: \n", reshapedArray)
print("4. \nUnpacked 1, ", a0)
print("Unpacked 2, ", a1)
print("Unpacked 3, ", b0)
print("Unpacked 4, ", b1)





1. New array: 
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

2. Sorted Array: 
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

3. Reshaped Array: 
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]
4. 
Unpacked 1,  [16 25  2]
Unpacked 2,  [11  4 13]
Unpacked 3,  [ 7 81  5]
Unpacked 4,  [ 6 11 12]


In [75]:
import numpy as np

one=np.array([10,11,12,13,14,15,16,17])
two=np.array([20,21,22,23,24,25,26,27])
three=np.array([0,1,2,3,4,5,6,7])

combarray=np.concatenate((one,two,three))
ComboArray=np.sort(combarray)
a=ComboArray[2]
b=ComboArray[3:27]
c=ComboArray[4:15]
d=ComboArray[-6:]
e=ComboArray[-24:14]
f=ComboArray[16:27:2]
g=ComboArray[-1:-24:-5]

print("\n5. \n", ComboArray)
print("\nSec1:\n ", a)
print("\nSec2:\n ", b)
print("\nSec3: \n", c)
print("\nSec4: \n", d)
print("\nSec5: \n", e)
print("\nSec6: \n", f)
print("\nSec7: \n", g)




5. 
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

Sec1:
  2

Sec2:
  [ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

Sec3: 
 [ 4  5  6  7 10 11 12 13 14 15 16]

Sec4: 
 [22 23 24 25 26 27]

Sec5: 
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]

Sec6: 
 [20 22 24 26]

Sec7: 
 [27 22 15 10  3]


In [83]:
import numpy as np

Array1=np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])
Array2=np.array([[17.0, 70.0, 10.7]])

Array3=np.add(Array1,Array2)
Array4=np.multiply(Array1,Array2)
Array5=np.divide(Array1,Array2)
divisible_by_3=Array3[Array3 % 3 ==0]

print("\n7. \n Adding: \n", Array3)
print("\nDividing: \n", Array4)
print("\nMultiplying: \n", Array5)
print("\nDivisible by 3: \n", divisible_by_3)



7. 
 Adding: 
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]

Dividing: 
 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]

Multiplying: 
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]

Divisible by 3: 
 [27.]


In [108]:
import pandas as pd

Ingredients=pd.Series(["Flour","Milk", "Eggs","Spam"], name='Ingredients')
Quantity=pd.Series([4,1,2,1], name='Quantity')
Unit=pd.Series(["cups","cups","large","can"], name='Unit')

df=pd.concat([Ingredients,Quantity,Unit], axis=1)
print("\n10. \nDataFrame1\n",df)


10. 
DataFrame1
   Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1   cups
2        Eggs         2  large
3        Spam         1    can


In [123]:
import pandas as pd


data = {'Name':['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Heights':[5.1, 6.2, 5.1, 5.2],
        'Qualifications':['Msc', 'MA', 'Msc', 'Msc'],
        'address':['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age':[21, 23, 24, 21],
        'Pets':['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sports':['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
}

df=df.assign(deserts=['ice cream','Cashew Fudge','waffels','Carrot Halwa'])

print("\nprint: \n", df)

df.sort_values(by=['Name','address'])


print: 
       Name  Heights Qualifications  address  Age        Pets          sports  \
0      Jai      5.1            Msc    Delhi   21         Dog           Darts   
1  janusha      6.2             MA     Doha   23       Bunny      Basketball   
2   Gaurav      5.1            Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj      5.2            Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


Name  Heights Qualifications  address  Age        Pets          sports  \
3     Anuj      5.2            Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav      5.1            Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai      5.1            Msc    Delhi   21         Dog           Darts   
1  janusha      6.2             MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

In [124]:
import pandas as pd

cows_and_goats=pd.DataFrame({'Cows':[12,20], 'Goats':[22,19]}, index=['Year 1', 'Year 2'])

cows_and_goats.to_csv('cows_ands_goats.csv')

In [126]:
import pandas as pd

vegetables=pd.DataFrame({'Name':['lettuce','carrots','cellary'],'color':['green','orange','light green']}, index=['veg1','veg2','veg3'])
vegetables.to_csv('vegetables.csv')


In [127]:
import pandas as pd

df=pd.read_csv("./vegetables.csv")
print(df.to_string())

  Unnamed: 0     Name        color
0       veg1  lettuce        green
1       veg2  carrots       orange
2       veg3  cellary  light green
